### ISSUE TITLE
Remove `grunt reformat` task; update from node-template once it is removed there

### ISSUE THREAD

**Issue by pjliddy** [ga-wdi-boston/js-this-prototype-study#162]
When I run grunt reformat as specified in the instructions, I get the following error message, regardless of which repo. It appears not to be entered in grunt/aliases.json.

```
$ grunt reformat
Warning: Task "reformat" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by jrhorn424** [comment]
Thanks for reporting! That task should be replaced by `grunt make-standard`.
